<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-QJLSV9M" failures="1" tests="8" name="com.api.FTValidations.LoginFTValidations" time="28.557" errors="1" timestamp="2023-05-16T13:56:32 IST" skipped="0">
  <testcase classname="com.api.FTValidations.LoginFTValidations" name="RestApiLoginValidations" time="9.951"/>
  <system-out>
    <![CDATA[Actual status code is =>200=>-AND-expected status code=>200
Actual Response body =>[{"jwt":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiN2MyMWM4YzEtM2VlMC01MGViLThlMDItNGRhZWExYjQ4YzEyIiwidXNlcl9jYXRlZ29yeSI6IkFkbWluIiwidXNlcl9jbGllbnRfaWQiOiJOLkEuIiwidXNlcl90eXBlIjoiTi5BLiIsImlhdCI6MTY4NDIyNTU5MH0.GWvumwkbAiPE8mUKM_-0qOf_iN4fI2phoYXifGPIihM"}]=>Expected Response Body is=>eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.
Actual Response body =>application/json; charset=utf-8=>Expected Response Body is=>application/json; charset=utf-8]]>
  </system-out>
  <testcase classname="com.api.FTValidations.LoginFTValidations" name="RestApiLoginValidations" time="0.181"/>
  <system-out>
    <![CDATA[Actual status code is =>400=>-AND-expected status code=>400
Actual Response body =>"User Email Doesn't Exists"=>Expected Response Body is=>User Email Doesn't Exists
Actual Response body =>application/json; charset=utf-8=>Expected Response Body is=>application/json; charset=utf-8]]>
  </system-out>
  <testcase classname="com.api.FTValidations.LoginFTValidations" name="RestApiLoginValidations" time="0.164"/>
  <system-out>
    <![CDATA[Actual status code is =>502=>-AND-expected status code=>502
Actual Response body =>{"message": "Internal server error"}=>Expected Response Body is=>Internal server error
Actual Response body =>application/json=>Expected Response Body is=>application/json]]>
  </system-out>
  <testcase classname="com.api.FTValidations.LoginFTValidations" name="RestApiLoginValidations" time="17.601">
    <error message="
[public void com.api.FTValidations.LoginFTValidations.RestApiLoginValidations(java.lang.String,java.lang.String,java.lang.String,double,java.lang.String,java.lang.String)] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: RestApiLoginValidations([java.lang.String arg0, java.lang.String arg1, java.lang.String arg2, double arg3, java.lang.String arg4, java.lang.String arg5])
Arguments: [null,null,null,null]" type="org.testng.internal.reflect.MethodMatcherException">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
[public void com.api.FTValidations.LoginFTValidations.RestApiLoginValidations(java.lang.String,java.lang.String,java.lang.String,double,java.lang.String,java.lang.String)] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: RestApiLoginValidations([java.lang.String arg0, java.lang.String arg1, java.lang.String arg2, double arg3, java.lang.String arg4, java.lang.String arg5])
Arguments: [null,null,null,null]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:46)
at org.testng.internal.Parameters.injectParameters(Parameters.java:909)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:37)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- RestApiLoginValidations -->
  <system-out/>
  <testcase classname="com.api.FTValidations.LoginFTValidations" name="RestApiLoginValidations" time="0.199"/>
  <system-out>
    <![CDATA[Actual status code is =>400=>-AND-expected status code=>400
Actual Response body =>"Invalid Password"=>Expected Response Body is=>Invalid Password
Actual Response body =>application/json; charset=utf-8=>Expected Response Body is=>application/json; charset=utf-8]]>
  </system-out>
  <testcase classname="com.api.FTValidations.LoginFTValidations" name="RestApiLoginValidations" time="0.164"/>
  <system-out>
    <![CDATA[Actual status code is =>400=>-AND-expected status code=>400
Actual Response body =>"Unexpected token } in JSON at position 98"=>Expected Response Body is=>Unexpected token } in JSON at position
Actual Response body =>application/json; charset=utf-8=>Expected Response Body is=>application/json; charset=utf-8]]>
  </system-out>
  <testcase classname="com.api.FTValidations.LoginFTValidations" name="RestApiLoginValidations" time="0.143"/>
  <system-out>
    <![CDATA[Actual status code is =>400=>-AND-expected status code=>400
Actual Response body =>"Unexpected string in JSON at position 75"=>Expected Response Body is=>Unexpected string in JSON at position
Actual Response body =>application/json; charset=utf-8=>Expected Response Body is=>application/json; charset=utf-8]]>
  </system-out>
  <testcase classname="com.api.FTValidations.LoginFTValidations" name="RestApiLoginValidations" time="0.154">
    <failure message="Expected status code is  Incorrect expected [400] but found [500]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Expected status code is  Incorrect expected [400] but found [500]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1418)
at org.testng.Assert.assertEquals(Assert.java:1382)
at com.api.FTValidations.LoginFTValidations.RestApiLoginValidations(LoginFTValidations.java:59)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- RestApiLoginValidations -->
  <system-out>
    <![CDATA[Actual status code is =>500=>-AND-expected status code=>400]]>
  </system-out>
</testsuite> <!-- com.api.FTValidations.LoginFTValidations -->
